### ISSUE TITLE
Create an example for how to get 3D position of object with patches.

### ISSUE THREAD

**Issue by lassemt** [Spark-AR-Community/SparkAR-Snippets#1]
Old way looks something like this:
`
Patches.setScalarValue("ballposX", sphere0.transform.x);
Patches.setScalarValue("ballposY", sphere0.transform.y);
`
[Source](https://www.facebook.com/groups/1120561154812425/permalink/1225476180987588/?comment_id=1225502610984945&reply_comment_id=1422307014637836)

Also, maybe add a wordTransform example in the same.

**Comment by rbkavin** [comment]
this is the last commit I made bro .

**Comment by lassemt** [comment]
Solved in #6
